version: "3.7"

# SERVICES
services:

  # MySQL
  db:
    image: mysql:8.0.28-oracle
    hostname: mysql
    container_name: ${APP_NAME}-db
    tty: false
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./.docker/mysql/prod.sql:/docker-entrypoint-initdb.d/prod.sql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ${APP_NAME}-volumes:/var/lib/mysql/
    networks:
      - ${APP_NAME}-network
    ports:
      - ${DB_PORT}:3306

  # Yii2
  php:
    image: "${REGISTRY_HOST}/${APP_NAME}-php"
    hostname: php
    build:
      context: "."
      target: deploy # set ke deploy saat akan production
      dockerfile: "./.docker/php/debian-apache/Dockerfile"
    container_name: ${APP_NAME}-php
    tty: true
    working_dir: /var/www/html
    ports:
      - "${WEB_SERVER_PORT}:80"
    env_file:
      - .env
    environment:
      - ENV=staging
      - TARGET=staging
    networks:
      - ${APP_NAME}-network
    depends_on:
      - db

# Docker Networks
networks:
  jameson_tools-network:
    name: jameson_tools-network
    driver: bridge

# Docker Volumes
volumes:
  jameson_tools-volumes:
    driver: local