<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\BuktiPengeluaranPettyCashCashAdvanceQuery;

/**
 * This is the base-model class for table "bukti_pengeluaran_petty_cash_cash_advance".
 *
 * @property integer $id
 * @property integer $bukti_pengeluaran_petty_cash_id
 * @property integer $job_order_detail_cash_advance_id
 *
 * @property \app\models\BuktiPenerimaanPettyCashCashAdvance $buktiPenerimaanPettyCashCashAdvance
 * @property \app\models\BuktiPengeluaranPettyCash $buktiPengeluaranPettyCash
 * @property \app\models\JobOrderDetailCashAdvance $jobOrderDetailCashAdvance
 */
abstract class BuktiPengeluaranPettyCashCashAdvance extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bukti_pengeluaran_petty_cash_cash_advance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['bukti_pengeluaran_petty_cash_id', 'job_order_detail_cash_advance_id'], 'required'],
            [['bukti_pengeluaran_petty_cash_id', 'job_order_detail_cash_advance_id'], 'integer'],
            [['bukti_pengeluaran_petty_cash_id'], 'unique'],
            [['job_order_detail_cash_advance_id'], 'unique'],
            [['bukti_pengeluaran_petty_cash_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPengeluaranPettyCash::class, 'targetAttribute' => ['bukti_pengeluaran_petty_cash_id' => 'id']],
            [['job_order_detail_cash_advance_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JobOrderDetailCashAdvance::class, 'targetAttribute' => ['job_order_detail_cash_advance_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'bukti_pengeluaran_petty_cash_id' => 'Bukti Pengeluaran Petty Cash ID',
            'job_order_detail_cash_advance_id' => 'Job Order Detail Cash Advance ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPenerimaanPettyCashCashAdvance()
    {
        return $this->hasOne(\app\models\BuktiPenerimaanPettyCashCashAdvance::class, ['bukti_pengeluaran_petty_cash_cash_advance_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPengeluaranPettyCash()
    {
        return $this->hasOne(\app\models\BuktiPengeluaranPettyCash::class, ['id' => 'bukti_pengeluaran_petty_cash_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderDetailCashAdvance()
    {
        return $this->hasOne(\app\models\JobOrderDetailCashAdvance::class, ['id' => 'job_order_detail_cash_advance_id']);
    }

    /**
     * @inheritdoc
     * @return BuktiPengeluaranPettyCashCashAdvanceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BuktiPengeluaranPettyCashCashAdvanceQuery(static::class);
    }
}
