<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\BuktiPenerimaanPettyCashCashAdvanceQuery;

/**
 * This is the base-model class for table "bukti_penerimaan_petty_cash_cash_advance".
 *
 * @property integer $id
 * @property integer $bukti_penerimaan_petty_cash_id
 * @property integer $bukti_pengeluaran_petty_cash_cash_advance_id
 *
 * @property \app\models\BuktiPenerimaanPettyCash $buktiPenerimaanPettyCash
 * @property \app\models\BuktiPengeluaranPettyCashCashAdvance $buktiPengeluaranPettyCashCashAdvance
 */
abstract class BuktiPenerimaanPettyCashCashAdvance extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bukti_penerimaan_petty_cash_cash_advance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['bukti_penerimaan_petty_cash_id', 'bukti_pengeluaran_petty_cash_cash_advance_id'], 'integer'],
            [['bukti_penerimaan_petty_cash_id'], 'unique'],
            [['bukti_pengeluaran_petty_cash_cash_advance_id'], 'unique'],
            [['bukti_penerimaan_petty_cash_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPenerimaanPettyCash::class, 'targetAttribute' => ['bukti_penerimaan_petty_cash_id' => 'id']],
            [['bukti_pengeluaran_petty_cash_cash_advance_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPengeluaranPettyCashCashAdvance::class, 'targetAttribute' => ['bukti_pengeluaran_petty_cash_cash_advance_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'bukti_penerimaan_petty_cash_id' => 'Bukti Penerimaan Petty Cash ID',
            'bukti_pengeluaran_petty_cash_cash_advance_id' => 'Bukti Pengeluaran Petty Cash Cash Advance ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPenerimaanPettyCash()
    {
        return $this->hasOne(\app\models\BuktiPenerimaanPettyCash::class, ['id' => 'bukti_penerimaan_petty_cash_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPengeluaranPettyCashCashAdvance()
    {
        return $this->hasOne(\app\models\BuktiPengeluaranPettyCashCashAdvance::class, ['id' => 'bukti_pengeluaran_petty_cash_cash_advance_id']);
    }

    /**
     * @inheritdoc
     * @return BuktiPenerimaanPettyCashCashAdvanceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BuktiPenerimaanPettyCashCashAdvanceQuery(static::class);
    }
}
