<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\active_queries\BuktiPengeluaranBukuBankQuery;

/**
 * This is the base-model class for table "bukti_pengeluaran_buku_bank".
 *
 * @property integer $id
 * @property string $reference_number
 * @property integer $rekening_saya_id
 * @property integer $jenis_transfer_id
 * @property integer $vendor_id
 * @property integer $vendor_rekening_id
 * @property string $nomor_bukti_transaksi
 * @property string $tanggal_transaksi
 * @property string $keterangan
 * @property integer $is_for_petty_cash
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\BukuBank $bukuBank
 * @property \app\models\JenisTransfer $jenisTransfer
 * @property \app\models\JobOrderBill[] $jobOrderBills
 * @property \app\models\JobOrderDetailCashAdvance[] $jobOrderDetailCashAdvances
 * @property \app\models\Rekening $rekeningSaya
 * @property \app\models\Card $vendor
 * @property \app\models\Rekening $vendorRekening
 */
abstract class BuktiPengeluaranBukuBank extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bukti_pengeluaran_buku_bank';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['rekening_saya_id', 'jenis_transfer_id', 'vendor_id', 'vendor_rekening_id', 'is_for_petty_cash'], 'integer'],
            [['tanggal_transaksi'], 'safe'],
            [['keterangan'], 'string'],
            [['reference_number'], 'string', 'max' => 50],
            [['nomor_bukti_transaksi'], 'string', 'max' => 255],
            [['rekening_saya_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Rekening::class, 'targetAttribute' => ['rekening_saya_id' => 'id']],
            [['jenis_transfer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JenisTransfer::class, 'targetAttribute' => ['jenis_transfer_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']],
            [['vendor_rekening_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Rekening::class, 'targetAttribute' => ['vendor_rekening_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'reference_number' => 'Reference Number',
            'rekening_saya_id' => 'Rekening Saya ID',
            'jenis_transfer_id' => 'Jenis Transfer ID',
            'vendor_id' => 'Vendor ID',
            'vendor_rekening_id' => 'Vendor Rekening ID',
            'nomor_bukti_transaksi' => 'Nomor Bukti Transaksi',
            'tanggal_transaksi' => 'Tanggal Transaksi',
            'keterangan' => 'Keterangan',
            'is_for_petty_cash' => 'Is For Petty Cash',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBukuBank()
    {
        return $this->hasOne(\app\models\BukuBank::class, ['bukti_pengeluaran_buku_bank_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisTransfer()
    {
        return $this->hasOne(\app\models\JenisTransfer::class, ['id' => 'jenis_transfer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderBills()
    {
        return $this->hasMany(\app\models\JobOrderBill::class, ['bukti_pengeluaran_buku_bank_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderDetailCashAdvances()
    {
        return $this->hasMany(\app\models\JobOrderDetailCashAdvance::class, ['bukti_pengeluaran_buku_bank_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRekeningSaya()
    {
        return $this->hasOne(\app\models\Rekening::class, ['id' => 'rekening_saya_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendorRekening()
    {
        return $this->hasOne(\app\models\Rekening::class, ['id' => 'vendor_rekening_id']);
    }

    /**
     * @inheritdoc
     * @return BuktiPengeluaranBukuBankQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BuktiPengeluaranBukuBankQuery(static::class);
    }
}
