<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\active_queries\BuktiPengeluaranPettyCashQuery;

/**
 * This is the base-model class for table "bukti_pengeluaran_petty_cash".
 *
 * @property integer $id
 * @property string $reference_number
 * @property integer $job_order_detail_cash_advance_id
 * @property integer $job_order_bill_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\BuktiPenerimaanPettyCash $buktiPenerimaanPettyCash
 * @property \app\models\JobOrderBill $jobOrderBill
 * @property \app\models\JobOrderDetailCashAdvance $jobOrderDetailCashAdvance
 * @property \app\models\MutasiKasPettyCash $mutasiKasPettyCash
 */
abstract class BuktiPengeluaranPettyCash extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bukti_pengeluaran_petty_cash';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['job_order_detail_cash_advance_id', 'job_order_bill_id'], 'integer'],
            [['reference_number'], 'string', 'max' => 255],
            [['job_order_detail_cash_advance_id'], 'unique'],
            [['job_order_bill_id'], 'unique'],
            [['job_order_detail_cash_advance_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JobOrderDetailCashAdvance::class, 'targetAttribute' => ['job_order_detail_cash_advance_id' => 'id']],
            [['job_order_bill_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JobOrderBill::class, 'targetAttribute' => ['job_order_bill_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'reference_number' => 'Reference Number',
            'job_order_detail_cash_advance_id' => 'Job Order Detail Cash Advance ID',
            'job_order_bill_id' => 'Job Order Bill ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPenerimaanPettyCash()
    {
        return $this->hasOne(\app\models\BuktiPenerimaanPettyCash::class, ['bukti_pengeluaran_petty_cash_cash_advance_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderBill()
    {
        return $this->hasOne(\app\models\JobOrderBill::class, ['id' => 'job_order_bill_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderDetailCashAdvance()
    {
        return $this->hasOne(\app\models\JobOrderDetailCashAdvance::class, ['id' => 'job_order_detail_cash_advance_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMutasiKasPettyCash()
    {
        return $this->hasOne(\app\models\MutasiKasPettyCash::class, ['bukti_pengeluaran_petty_cash_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return BuktiPengeluaranPettyCashQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BuktiPengeluaranPettyCashQuery(static::class);
    }
}
