<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\active_queries\BuktiPenerimaanPettyCashQuery;

/**
 * This is the base-model class for table "bukti_penerimaan_petty_cash".
 *
 * @property integer $id
 * @property string $reference_number
 * @property integer $bukti_pengeluaran_petty_cash_cash_advance_id
 * @property integer $buku_bank_id
 * @property string $tanggal_transaksi
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\BuktiPengeluaranPettyCash $buktiPengeluaranPettyCashCashAdvance
 * @property \app\models\BukuBank $bukuBank
 * @property \app\models\MutasiKasPettyCash $mutasiKasPettyCash
 */
abstract class BuktiPenerimaanPettyCash extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bukti_penerimaan_petty_cash';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['bukti_pengeluaran_petty_cash_cash_advance_id', 'buku_bank_id'], 'integer'],
            [['tanggal_transaksi'], 'required'],
            [['tanggal_transaksi'], 'safe'],
            [['reference_number'], 'string', 'max' => 50],
            [['bukti_pengeluaran_petty_cash_cash_advance_id'], 'unique'],
            [['buku_bank_id'], 'unique'],
            [['bukti_pengeluaran_petty_cash_cash_advance_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPengeluaranPettyCash::class, 'targetAttribute' => ['bukti_pengeluaran_petty_cash_cash_advance_id' => 'id']],
            [['buku_bank_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BukuBank::class, 'targetAttribute' => ['buku_bank_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'reference_number' => 'Reference Number',
            'bukti_pengeluaran_petty_cash_cash_advance_id' => 'Bukti Pengeluaran Petty Cash Cash Advance ID',
            'buku_bank_id' => 'Buku Bank ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'tanggal_transaksi' => 'Tanggal Transaksi',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPengeluaranPettyCashCashAdvance()
    {
        return $this->hasOne(\app\models\BuktiPengeluaranPettyCash::class, ['id' => 'bukti_pengeluaran_petty_cash_cash_advance_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBukuBank()
    {
        return $this->hasOne(\app\models\BukuBank::class, ['id' => 'buku_bank_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMutasiKasPettyCash()
    {
        return $this->hasOne(\app\models\MutasiKasPettyCash::class, ['bukti_penerimaan_petty_cash_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return BuktiPenerimaanPettyCashQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BuktiPenerimaanPettyCashQuery(static::class);
    }
}
