<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "card_own_equipment_history".
 *
 * @property integer $id
 * @property integer $card_own_equipment_id
 * @property string $tanggal_service_saat_ini
 * @property integer $hour_meter_saat_ini
 * @property string $kondisi_terakhir
 * @property integer $service_terakhir
 * @property integer $service_selanjutnya
 * @property integer $hour_meter_service_selanjutnya
 * @property string $tanggal_service_selanjutnya
 *
 * @property \app\models\CardOwnEquipment $cardOwnEquipment
 * @property string $aliasModel
 */
abstract class CardOwnEquipmentHistory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'card_own_equipment_history';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['card_own_equipment_id', 'hour_meter_saat_ini', 'service_terakhir', 'service_selanjutnya', 'hour_meter_service_selanjutnya'], 'integer'],
            [['tanggal_service_saat_ini', 'hour_meter_saat_ini', 'kondisi_terakhir', 'tanggal_service_selanjutnya'], 'required'],
            [['tanggal_service_saat_ini', 'tanggal_service_selanjutnya'], 'safe'],
            [['kondisi_terakhir'], 'string'],
            [['card_own_equipment_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CardOwnEquipment::class, 'targetAttribute' => ['card_own_equipment_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'card_own_equipment_id' => 'Card Own Equipment ID',
            'tanggal_service_saat_ini' => 'Tanggal Service Saat Ini',
            'hour_meter_saat_ini' => 'Hour Meter Saat Ini',
            'kondisi_terakhir' => 'Kondisi Terakhir',
            'service_terakhir' => 'Service Terakhir',
            'service_selanjutnya' => 'Service Selanjutnya',
            'hour_meter_service_selanjutnya' => 'Hour Meter Service Selanjutnya',
            'tanggal_service_selanjutnya' => 'Tanggal Service Selanjutnya',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCardOwnEquipment()
    {
        return $this->hasOne(\app\models\CardOwnEquipment::class, ['id' => 'card_own_equipment_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\CardOwnEquipmentHistoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\CardOwnEquipmentHistoryQuery(get_called_class());
    }


}
