<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "card_person_in_charge".
 *
 * @property integer $id
 * @property integer $card_id
 * @property string $nama
 * @property string $telepon
 * @property string $email
 *
 * @property \app\models\Card $card
 * @property string $aliasModel
 */
abstract class CardPersonInCharge extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'card_person_in_charge';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['card_id', 'nama'], 'required'],
            [['card_id'], 'integer'],
            [['nama', 'telepon', 'email'], 'string', 'max' => 255],
            [['card_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['card_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'card_id' => 'Card ID',
            'nama' => 'Nama',
            'telepon' => 'Telepon',
            'email' => 'Email',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCard()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'card_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\CardPersonInChargeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\CardPersonInChargeQuery(get_called_class());
    }


}
