<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "claim_petty_cash_nota".
 *
 * @property integer $id
 * @property integer $claim_petty_cash_id
 * @property string $nomor
 * @property integer $vendor_id
 * @property string $tanggal_nota
 *
 * @property \app\models\ClaimPettyCash $claimPettyCash
 * @property \app\models\ClaimPettyCashNotaDetail[] $claimPettyCashNotaDetails
 * @property \app\models\Card $vendor
 * @property string $aliasModel
 */
abstract class ClaimPettyCashNota extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'claim_petty_cash_nota';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['claim_petty_cash_id', 'vendor_id'], 'integer'],
            [['nomor', 'vendor_id', 'tanggal_nota'], 'required'],
            [['tanggal_nota'], 'safe'],
            [['nomor'], 'string', 'max' => 128],
            [['claim_petty_cash_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ClaimPettyCash::class, 'targetAttribute' => ['claim_petty_cash_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'claim_petty_cash_id' => 'Claim Petty Cash ID',
            'nomor' => 'Nomor',
            'vendor_id' => 'Vendor ID',
            'tanggal_nota' => 'Tanggal Nota',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClaimPettyCash()
    {
        return $this->hasOne(\app\models\ClaimPettyCash::class, ['id' => 'claim_petty_cash_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClaimPettyCashNotaDetails()
    {
        return $this->hasMany(\app\models\ClaimPettyCashNotaDetail::class, ['claim_petty_cash_nota_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\ClaimPettyCashNotaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\ClaimPettyCashNotaQuery(get_called_class());
    }


}
