<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "claim_petty_cash_nota_detail".
 *
 * @property integer $id
 * @property integer $claim_petty_cash_nota_id
 * @property integer $barang_id
 * @property string $description
 * @property string $quantity
 * @property integer $satuan_id
 * @property string $harga
 *
 * @property \app\models\Barang $barang
 * @property \app\models\ClaimPettyCashNota $claimPettyCashNota
 * @property \app\models\HistoryLokasiBarang[] $historyLokasiBarangs
 * @property \app\models\Satuan $satuan
 * @property string $aliasModel
 */
abstract class ClaimPettyCashNotaDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'claim_petty_cash_nota_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['claim_petty_cash_nota_id', 'barang_id', 'satuan_id'], 'integer'],
            [['quantity', 'satuan_id', 'harga'], 'required'],
            [['quantity', 'harga'], 'number'],
            [['description'], 'string', 'max' => 255],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']],
            [['claim_petty_cash_nota_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ClaimPettyCashNota::class, 'targetAttribute' => ['claim_petty_cash_nota_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'claim_petty_cash_nota_id' => 'Claim Petty Cash Nota ID',
            'barang_id' => 'Barang ID',
            'description' => 'Description',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
            'harga' => 'Harga',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClaimPettyCashNota()
    {
        return $this->hasOne(\app\models\ClaimPettyCashNota::class, ['id' => 'claim_petty_cash_nota_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHistoryLokasiBarangs()
    {
        return $this->hasMany(\app\models\HistoryLokasiBarang::class, ['claim_petty_cash_nota_detail_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\ClaimPettyCashNotaDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\ClaimPettyCashNotaDetailQuery(get_called_class());
    }


}
