<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "inventaris".
 *
 * @property integer $id
 * @property integer $material_requisition_detail_penawaran_id
 * @property string $kode_inventaris
 * @property integer $location_id
 * @property string $quantity
 *
 * @property \app\models\InventarisLaporanPerbaikanDetail[] $inventarisLaporanPerbaikanDetails
 * @property \app\models\Card $location
 * @property \app\models\MaterialRequisitionDetailPenawaran $materialRequisitionDetailPenawaran
 * @property string $aliasModel
 */
abstract class Inventaris extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventaris';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['material_requisition_detail_penawaran_id', 'location_id'], 'integer'],
            [['location_id'], 'required'],
            [['quantity'], 'number'],
            [['kode_inventaris'], 'string', 'max' => 255],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['location_id' => 'id']],
            [['material_requisition_detail_penawaran_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MaterialRequisitionDetailPenawaran::class, 'targetAttribute' => ['material_requisition_detail_penawaran_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'material_requisition_detail_penawaran_id' => 'Material Requisition Detail Penawaran ID',
            'kode_inventaris' => 'Kode Inventaris',
            'location_id' => 'Location ID',
            'quantity' => 'Quantity',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'location_id' => 'Card Tipe Warehouse',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInventarisLaporanPerbaikanDetails()
    {
        return $this->hasMany(\app\models\InventarisLaporanPerbaikanDetail::class, ['inventaris_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'location_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaterialRequisitionDetailPenawaran()
    {
        return $this->hasOne(\app\models\MaterialRequisitionDetailPenawaran::class, ['id' => 'material_requisition_detail_penawaran_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\InventarisQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\InventarisQuery(get_called_class());
    }


}
