<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "inventaris_laporan_perbaikan_master".
 *
 * @property integer $id
 * @property string $nomor
 * @property string $tanggal
 * @property integer $card_id
 * @property integer $status_id
 * @property string $comment
 * @property integer $approved_by_id
 * @property integer $known_by_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\Card $approvedBy
 * @property \app\models\Card $card
 * @property \app\models\InventarisLaporanPerbaikanDetail[] $inventarisLaporanPerbaikanDetails
 * @property \app\models\Card $knownBy
 * @property \app\models\Status $status
 * @property string $aliasModel
 */
abstract class InventarisLaporanPerbaikanMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventaris_laporan_perbaikan_master';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['tanggal', 'card_id', 'status_id', 'approved_by_id', 'known_by_id'], 'required'],
            [['tanggal'], 'safe'],
            [['card_id', 'status_id', 'approved_by_id', 'known_by_id'], 'integer'],
            [['comment'], 'string'],
            [['nomor'], 'string', 'max' => 255],
            [['approved_by_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['approved_by_id' => 'id']],
            [['card_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['card_id' => 'id']],
            [['known_by_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['known_by_id' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Status::class, 'targetAttribute' => ['status_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nomor' => 'Nomor',
            'tanggal' => 'Tanggal',
            'card_id' => 'Card ID',
            'status_id' => 'Status ID',
            'comment' => 'Comment',
            'approved_by_id' => 'Approved By ID',
            'known_by_id' => 'Known By ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'card_id' => 'To',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApprovedBy()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'approved_by_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCard()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'card_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInventarisLaporanPerbaikanDetails()
    {
        return $this->hasMany(\app\models\InventarisLaporanPerbaikanDetail::class, ['inventaris_laporan_perbaikan_master_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKnownBy()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'known_by_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(\app\models\Status::class, ['id' => 'status_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\InventarisLaporanPerbaikanMasterQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\InventarisLaporanPerbaikanMasterQuery(get_called_class());
    }


}
