<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "inventaris_laporan_perbaikan_detail".
 *
 * @property integer $id
 * @property integer $inventaris_laporan_perbaikan_master_id
 * @property integer $inventaris_id
 * @property integer $kondisi_id
 * @property integer $last_location_id
 * @property string $last_repaired
 * @property string $remarks
 * @property string $estimated_price
 *
 * @property \app\models\Inventaris $inventaris
 * @property \app\models\InventarisLaporanPerbaikanMaster $inventarisLaporanPerbaikanMaster
 * @property \app\models\Status $kondisi
 * @property \app\models\Card $lastLocation
 * @property string $aliasModel
 */
abstract class InventarisLaporanPerbaikanDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventaris_laporan_perbaikan_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['inventaris_laporan_perbaikan_master_id', 'inventaris_id', 'kondisi_id', 'last_location_id'], 'integer'],
            [['last_location_id', 'last_repaired'], 'required'],
            [['last_repaired'], 'safe'],
            [['remarks'], 'string'],
            [['estimated_price'], 'number'],
            [['inventaris_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Inventaris::class, 'targetAttribute' => ['inventaris_id' => 'id']],
            [['inventaris_laporan_perbaikan_master_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InventarisLaporanPerbaikanMaster::class, 'targetAttribute' => ['inventaris_laporan_perbaikan_master_id' => 'id']],
            [['kondisi_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Status::class, 'targetAttribute' => ['kondisi_id' => 'id']],
            [['last_location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['last_location_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'inventaris_laporan_perbaikan_master_id' => 'Inventaris Laporan Perbaikan Master ID',
            'inventaris_id' => 'Inventaris ID',
            'kondisi_id' => 'Kondisi ID',
            'last_location_id' => 'Last Location ID',
            'last_repaired' => 'Last Repaired',
            'remarks' => 'Remarks',
            'estimated_price' => 'Estimated Price',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInventaris()
    {
        return $this->hasOne(\app\models\Inventaris::class, ['id' => 'inventaris_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInventarisLaporanPerbaikanMaster()
    {
        return $this->hasOne(\app\models\InventarisLaporanPerbaikanMaster::class, ['id' => 'inventaris_laporan_perbaikan_master_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKondisi()
    {
        return $this->hasOne(\app\models\Status::class, ['id' => 'kondisi_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLastLocation()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'last_location_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\InventarisLaporanPerbaikanDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\InventarisLaporanPerbaikanDetailQuery(get_called_class());
    }


}
