<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\InvoiceDetailQuery;

/**
 * This is the base-model class for table "invoice_detail".
 *
 * @property integer $id
 * @property integer $invoice_id
 * @property string $quantity
 * @property integer $satuan_id
 * @property integer $barang_id
 * @property string $harga
 *
 * @property \app\models\Barang $barang
 * @property \app\models\Invoice $invoice
 * @property \app\models\Satuan $satuan
 */
abstract class InvoiceDetail extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoice_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['invoice_id', 'satuan_id', 'barang_id'], 'integer'],
            [['quantity', 'harga'], 'number'],
            [['invoice_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Invoice::class, 'targetAttribute' => ['invoice_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'invoice_id' => 'Invoice ID',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
            'barang_id' => 'Barang ID',
            'harga' => 'Harga',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'invoice_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }

    /**
     * @inheritdoc
     * @return InvoiceDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new InvoiceDetailQuery(static::class);
    }
}
