<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\active_queries\InvoiceQuery;

/**
 * This is the base-model class for table "invoice".
 *
 * @property integer $id
 * @property string $reference_number
 * @property integer $customer_id
 * @property string $tanggal_invoice
 * @property integer $nomor_rekening_tagihan_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\Card $customer
 * @property \app\models\InvoiceDetail[] $invoiceDetails
 * @property \app\models\Rekening $nomorRekeningTagihan
 */
abstract class Invoice extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoice';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['customer_id', 'tanggal_invoice', 'nomor_rekening_tagihan_id'], 'required'],
            [['customer_id', 'nomor_rekening_tagihan_id'], 'integer'],
            [['tanggal_invoice'], 'safe'],
            [['reference_number'], 'string', 'max' => 255],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['customer_id' => 'id']],
            [['nomor_rekening_tagihan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Rekening::class, 'targetAttribute' => ['nomor_rekening_tagihan_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'reference_number' => 'Reference Number',
            'customer_id' => 'Customer ID',
            'tanggal_invoice' => 'Tanggal Invoice',
            'nomor_rekening_tagihan_id' => 'Nomor Rekening Tagihan ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoiceDetails()
    {
        return $this->hasMany(\app\models\InvoiceDetail::class, ['invoice_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNomorRekeningTagihan()
    {
        return $this->hasOne(\app\models\Rekening::class, ['id' => 'nomor_rekening_tagihan_id']);
    }

    /**
     * @inheritdoc
     * @return InvoiceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new InvoiceQuery(static::class);
    }
}
