<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\active_queries\JenisBiayaQuery;

/**
 * This is the base-model class for table "jenis_biaya".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $category
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\JobOrderBillDetail[] $jobOrderBillDetails
 * @property \app\models\JobOrderDetailCashAdvance[] $jobOrderDetailCashAdvances
 * @property \app\models\TransaksiBukuBankLainnya[] $transaksiBukuBankLainnyas
 * @property \app\models\TransaksiMutasiKasPettyCashLainnya[] $transaksiMutasiKasPettyCashLainnyas
 */
abstract class JenisBiaya extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jenis_biaya';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['name'], 'required'],
            [['description'], 'string'],
            [['category'], 'integer'],
            [['name'], 'string', 'max' => 50]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'category' => 'Category',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderBillDetails()
    {
        return $this->hasMany(\app\models\JobOrderBillDetail::class, ['jenis_biaya_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderDetailCashAdvances()
    {
        return $this->hasMany(\app\models\JobOrderDetailCashAdvance::class, ['jenis_biaya_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransaksiBukuBankLainnyas()
    {
        return $this->hasMany(\app\models\TransaksiBukuBankLainnya::class, ['jenis_biaya_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransaksiMutasiKasPettyCashLainnyas()
    {
        return $this->hasMany(\app\models\TransaksiMutasiKasPettyCashLainnya::class, ['jenis_biaya_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return JenisBiayaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JenisBiayaQuery(static::class);
    }
}
