<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\JobOrderDetailCashAdvanceQuery;

/**
 * This is the base-model class for table "job_order_detail_cash_advance".
 *
 * @property integer $id
 * @property integer $job_order_id
 * @property integer $vendor_id
 * @property integer $jenis_biaya_id
 * @property integer $mata_uang_id
 * @property string $kasbon_request
 * @property string $cash_advance
 * @property integer $order
 *
 * @property \app\models\BuktiPengeluaranPettyCash $buktiPengeluaranPettyCash
 * @property \app\models\JenisBiaya $jenisBiaya
 * @property \app\models\JobOrder $jobOrder
 * @property \app\models\MataUang $mataUang
 * @property \app\models\Card $vendor
 */
abstract class JobOrderDetailCashAdvance extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'job_order_detail_cash_advance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['job_order_id', 'vendor_id', 'jenis_biaya_id', 'mata_uang_id', 'order'], 'integer'],
            [['vendor_id', 'jenis_biaya_id', 'mata_uang_id'], 'required'],
            [['kasbon_request', 'cash_advance'], 'number'],
            [['mata_uang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MataUang::class, 'targetAttribute' => ['mata_uang_id' => 'id']],
            [['job_order_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JobOrder::class, 'targetAttribute' => ['job_order_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']],
            [['jenis_biaya_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JenisBiaya::class, 'targetAttribute' => ['jenis_biaya_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'job_order_id' => 'Job Order ID',
            'vendor_id' => 'Vendor ID',
            'jenis_biaya_id' => 'Jenis Biaya ID',
            'mata_uang_id' => 'Mata Uang ID',
            'kasbon_request' => 'Kasbon Request',
            'cash_advance' => 'Cash Advance',
            'order' => 'Order',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'kasbon_request' => 'Kasbon',
            'cash_advance' => 'Panjar',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPengeluaranPettyCash()
    {
        return $this->hasOne(\app\models\BuktiPengeluaranPettyCash::class, ['job_order_detail_cash_advance_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisBiaya()
    {
        return $this->hasOne(\app\models\JenisBiaya::class, ['id' => 'jenis_biaya_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrder()
    {
        return $this->hasOne(\app\models\JobOrder::class, ['id' => 'job_order_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMataUang()
    {
        return $this->hasOne(\app\models\MataUang::class, ['id' => 'mata_uang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }

    /**
     * @inheritdoc
     * @return JobOrderDetailCashAdvanceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JobOrderDetailCashAdvanceQuery(static::class);
    }
}
