<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\JobOrderDetailPettyCashQuery;

/**
 * This is the base-model class for table "job_order_detail_petty_cash".
 *
 * @property integer $id
 * @property integer $job_order_id
 * @property integer $vendor_id
 * @property integer $jenis_biaya_id
 * @property integer $mata_uang_id
 * @property string $nominal
 * @property integer $bukti_pengeluaran_buku_bank_id
 *
 * @property \app\models\BuktiPengeluaranBukuBank $buktiPengeluaranBukuBank
 * @property \app\models\JenisBiaya $jenisBiaya
 * @property \app\models\JobOrder $jobOrder
 * @property \app\models\MataUang $mataUang
 * @property \app\models\Card $vendor
 */
abstract class JobOrderDetailPettyCash extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'job_order_detail_petty_cash';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['job_order_id', 'vendor_id', 'jenis_biaya_id', 'mata_uang_id', 'bukti_pengeluaran_buku_bank_id'], 'integer'],
            [['vendor_id', 'jenis_biaya_id', 'mata_uang_id', 'nominal'], 'required'],
            [['nominal'], 'number'],
            [['job_order_id'], 'unique'],
            [['bukti_pengeluaran_buku_bank_id'], 'unique'],
            [['job_order_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JobOrder::class, 'targetAttribute' => ['job_order_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']],
            [['jenis_biaya_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JenisBiaya::class, 'targetAttribute' => ['jenis_biaya_id' => 'id']],
            [['mata_uang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MataUang::class, 'targetAttribute' => ['mata_uang_id' => 'id']],
            [['bukti_pengeluaran_buku_bank_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPengeluaranBukuBank::class, 'targetAttribute' => ['bukti_pengeluaran_buku_bank_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'job_order_id' => 'Job Order ID',
            'vendor_id' => 'Vendor ID',
            'jenis_biaya_id' => 'Jenis Biaya ID',
            'mata_uang_id' => 'Mata Uang ID',
            'nominal' => 'Nominal',
            'bukti_pengeluaran_buku_bank_id' => 'Bukti Pengeluaran Buku Bank ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPengeluaranBukuBank()
    {
        return $this->hasOne(\app\models\BuktiPengeluaranBukuBank::class, ['id' => 'bukti_pengeluaran_buku_bank_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisBiaya()
    {
        return $this->hasOne(\app\models\JenisBiaya::class, ['id' => 'jenis_biaya_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrder()
    {
        return $this->hasOne(\app\models\JobOrder::class, ['id' => 'job_order_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMataUang()
    {
        return $this->hasOne(\app\models\MataUang::class, ['id' => 'mata_uang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }

    /**
     * @inheritdoc
     * @return JobOrderDetailPettyCashQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JobOrderDetailPettyCashQuery(static::class);
    }
}
