<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\JobOrderBillQuery;

/**
 * This is the base-model class for table "job_order_bill".
 *
 * @property integer $id
 * @property integer $job_order_id
 * @property integer $vendor_id
 * @property string $reference_number
 *
 * @property \app\models\BuktiPengeluaranPettyCash $buktiPengeluaranPettyCash
 * @property \app\models\JobOrder $jobOrder
 * @property \app\models\JobOrderBillDetail[] $jobOrderBillDetails
 * @property \app\models\Card $vendor
 */
abstract class JobOrderBill extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'job_order_bill';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['job_order_id', 'vendor_id'], 'integer'],
            [['vendor_id', 'reference_number'], 'required'],
            [['reference_number'], 'string', 'max' => 255],
            [['job_order_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JobOrder::class, 'targetAttribute' => ['job_order_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'job_order_id' => 'Job Order ID',
            'vendor_id' => 'Vendor ID',
            'reference_number' => 'Reference Number',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPengeluaranPettyCash()
    {
        return $this->hasOne(\app\models\BuktiPengeluaranPettyCash::class, ['job_order_bill_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrder()
    {
        return $this->hasOne(\app\models\JobOrder::class, ['id' => 'job_order_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderBillDetails()
    {
        return $this->hasMany(\app\models\JobOrderBillDetail::class, ['job_order_bill_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }

    /**
     * @inheritdoc
     * @return JobOrderBillQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JobOrderBillQuery(static::class);
    }
}
