<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\MataUangQuery;

/**
 * This is the base-model class for table "mata_uang".
 *
 * @property integer $id
 * @property string $negara
 * @property string $nama
 * @property string $kode
 * @property string $singkatan
 *
 * @property \app\models\Card[] $cards
 * @property \app\models\JobOrderDetailCashAdvance[] $jobOrderDetailCashAdvances
 * @property \app\models\JobOrderDetailPettyCash[] $jobOrderDetailPettyCashes
 * @property \app\models\MaterialRequisitionDetailPenawaran[] $materialRequisitionDetailPenawarans
 * @property \app\models\Quotation[] $quotations
 */
abstract class MataUang extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mata_uang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['negara', 'nama'], 'string', 'max' => 255],
            [['kode', 'singkatan'], 'string', 'max' => 16],
            [['nama'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'negara' => 'Negara',
            'nama' => 'Nama',
            'kode' => 'Kode',
            'singkatan' => 'Singkatan',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'nama' => 'eg, Rupiah, Dollar Amerika, Dollar Singapore',
            'kode' => 'eg. IDR, USD',
            'singkatan' => 'eg. `Rp.` , USD. ',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCards()
    {
        return $this->hasMany(\app\models\Card::class, ['mata_uang_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderDetailCashAdvances()
    {
        return $this->hasMany(\app\models\JobOrderDetailCashAdvance::class, ['mata_uang_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobOrderDetailPettyCashes()
    {
        return $this->hasMany(\app\models\JobOrderDetailPettyCash::class, ['mata_uang_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaterialRequisitionDetailPenawarans()
    {
        return $this->hasMany(\app\models\MaterialRequisitionDetailPenawaran::class, ['mata_uang_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotations()
    {
        return $this->hasMany(\app\models\Quotation::class, ['mata_uang_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return MataUangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MataUangQuery(static::class);
    }
}
