<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "mata_uang".
 *
 * @property integer $id
 * @property string $negara
 * @property string $nama
 * @property string $kode
 * @property string $singkatan
 *
 * @property \app\models\Card[] $cards
 * @property \app\models\MaterialRequisitionDetailPenawaran[] $materialRequisitionDetailPenawarans
 * @property string $aliasModel
 */
abstract class MataUang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mata_uang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['negara', 'nama'], 'string', 'max' => 255],
            [['kode', 'singkatan'], 'string', 'max' => 16],
            [['nama'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'negara' => 'Negara',
            'nama' => 'Nama',
            'kode' => 'Kode',
            'singkatan' => 'Singkatan',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nama' => 'eg, Rupiah, Dollar Amerika, Dollar Singapore',
            'kode' => 'eg. IDR, USD',
            'singkatan' => 'eg. `Rp.` , USD. ',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCards()
    {
        return $this->hasMany(\app\models\Card::class, ['mata_uang_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaterialRequisitionDetailPenawarans()
    {
        return $this->hasMany(\app\models\MaterialRequisitionDetailPenawaran::class, ['mata_uang_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\MataUangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\MataUangQuery(get_called_class());
    }


}
