<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "material_requisition_detail".
 *
 * @property integer $id
 * @property integer $material_requisition_id
 * @property integer $barang_id
 * @property string $description
 * @property string $quantity
 * @property integer $satuan_id
 * @property integer $vendor_id
 * @property string $waktu_permintaan_terakhir
 * @property string $harga_terakhir
 * @property string $stock_terakhir
 *
 * @property \app\models\Barang $barang
 * @property \app\models\MaterialRequisition $materialRequisition
 * @property \app\models\MaterialRequisitionDetailPenawaran[] $materialRequisitionDetailPenawarans
 * @property \app\models\Satuan $satuan
 * @property \app\models\Card $vendor
 * @property string $aliasModel
 */
abstract class MaterialRequisitionDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'material_requisition_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['material_requisition_id', 'barang_id', 'satuan_id', 'vendor_id'], 'integer'],
            [['barang_id', 'quantity', 'satuan_id'], 'required'],
            [['quantity', 'harga_terakhir', 'stock_terakhir'], 'number'],
            [['waktu_permintaan_terakhir'], 'safe'],
            [['description'], 'string', 'max' => 255],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']],
            [['material_requisition_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MaterialRequisition::class, 'targetAttribute' => ['material_requisition_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'material_requisition_id' => 'Material Requisition ID',
            'barang_id' => 'Barang ID',
            'description' => 'Description',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
            'vendor_id' => 'Vendor ID',
            'waktu_permintaan_terakhir' => 'Waktu Permintaan Terakhir',
            'harga_terakhir' => 'Harga Terakhir',
            'stock_terakhir' => 'Stock Terakhir',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaterialRequisition()
    {
        return $this->hasOne(\app\models\MaterialRequisition::class, ['id' => 'material_requisition_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaterialRequisitionDetailPenawarans()
    {
        return $this->hasMany(\app\models\MaterialRequisitionDetailPenawaran::class, ['material_requisition_detail_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\MaterialRequisitionDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\MaterialRequisitionDetailQuery(get_called_class());
    }


}
