<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\MutasiKasPettyCashQuery;

/**
 * This is the base-model class for table "mutasi_kas_petty_cash".
 *
 * @property integer $id
 * @property integer $kode_voucher_id
 * @property integer $bukti_penerimaan_petty_cash_id
 * @property integer $bukti_pengeluaran_petty_cash_id
 * @property string $nomor_voucher
 * @property string $tanggal_mutasi
 * @property string $keterangan
 *
 * @property \app\models\BuktiPenerimaanPettyCash $buktiPenerimaanPettyCash
 * @property \app\models\BuktiPengeluaranPettyCash $buktiPengeluaranPettyCash
 * @property \app\models\KodeVoucher $kodeVoucher
 * @property \app\models\TransaksiMutasiKasPettyCashLainnya $transaksiMutasiKasPettyCashLainnya
 */
abstract class MutasiKasPettyCash extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mutasi_kas_petty_cash';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['kode_voucher_id', 'tanggal_mutasi'], 'required'],
            [['kode_voucher_id', 'bukti_penerimaan_petty_cash_id', 'bukti_pengeluaran_petty_cash_id'], 'integer'],
            [['tanggal_mutasi'], 'safe'],
            [['keterangan'], 'string'],
            [['nomor_voucher'], 'string', 'max' => 255],
            [['bukti_penerimaan_petty_cash_id'], 'unique'],
            [['bukti_pengeluaran_petty_cash_id'], 'unique'],
            [['bukti_penerimaan_petty_cash_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPenerimaanPettyCash::class, 'targetAttribute' => ['bukti_penerimaan_petty_cash_id' => 'id']],
            [['bukti_pengeluaran_petty_cash_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPengeluaranPettyCash::class, 'targetAttribute' => ['bukti_pengeluaran_petty_cash_id' => 'id']],
            [['kode_voucher_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\KodeVoucher::class, 'targetAttribute' => ['kode_voucher_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'kode_voucher_id' => 'Kode Voucher ID',
            'bukti_penerimaan_petty_cash_id' => 'Bukti Penerimaan Petty Cash ID',
            'bukti_pengeluaran_petty_cash_id' => 'Bukti Pengeluaran Petty Cash ID',
            'nomor_voucher' => 'Nomor Voucher',
            'tanggal_mutasi' => 'Tanggal Mutasi',
            'keterangan' => 'Keterangan',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPenerimaanPettyCash()
    {
        return $this->hasOne(\app\models\BuktiPenerimaanPettyCash::class, ['id' => 'bukti_penerimaan_petty_cash_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPengeluaranPettyCash()
    {
        return $this->hasOne(\app\models\BuktiPengeluaranPettyCash::class, ['id' => 'bukti_pengeluaran_petty_cash_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKodeVoucher()
    {
        return $this->hasOne(\app\models\KodeVoucher::class, ['id' => 'kode_voucher_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransaksiMutasiKasPettyCashLainnya()
    {
        return $this->hasOne(\app\models\TransaksiMutasiKasPettyCashLainnya::class, ['mutasi_kas_petty_cash_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return MutasiKasPettyCashQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MutasiKasPettyCashQuery(static::class);
    }
}
