<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "proforma_debit_note".
 *
 * @property integer $id
 * @property integer $quotation_id
 * @property string $nomor
 * @property string $tanggal
 * @property integer $pph_23_percent
 *
 * @property \app\models\ProformaDebitNoteDetailBarang[] $proformaDebitNoteDetailBarangs
 * @property \app\models\ProformaDebitNoteDetailService[] $proformaDebitNoteDetailServices
 * @property \app\models\Quotation $quotation
 * @property string $aliasModel
 */
abstract class ProformaDebitNote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'proforma_debit_note';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['quotation_id'], 'required'],
            [['quotation_id', 'pph_23_percent'], 'integer'],
            [['tanggal'], 'safe'],
            [['nomor'], 'string', 'max' => 128],
            [['quotation_id'], 'unique'],
            [['quotation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Quotation::class, 'targetAttribute' => ['quotation_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'quotation_id' => 'Quotation ID',
            'nomor' => 'Nomor',
            'tanggal' => 'Tanggal',
            'pph_23_percent' => 'Pph 23 Percent',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProformaDebitNoteDetailBarangs()
    {
        return $this->hasMany(\app\models\ProformaDebitNoteDetailBarang::class, ['proforma_debit_note_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProformaDebitNoteDetailServices()
    {
        return $this->hasMany(\app\models\ProformaDebitNoteDetailService::class, ['proforma_debit_note_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotation()
    {
        return $this->hasOne(\app\models\Quotation::class, ['id' => 'quotation_id']);
    }




}
