<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "proforma_invoice_detail_barang".
 *
 * @property integer $id
 * @property integer $proforma_invoice_id
 * @property integer $barang_id
 * @property string $stock
 * @property string $quantity
 * @property integer $satuan_id
 * @property string $unit_price
 * @property integer $discount
 * @property integer $is_vat
 *
 * @property \app\models\Barang $barang
 * @property \app\models\ProformaInvoice $proformaInvoice
 * @property \app\models\Satuan $satuan
 * @property string $aliasModel
 */
abstract class ProformaInvoiceDetailBarang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'proforma_invoice_detail_barang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['proforma_invoice_id', 'barang_id', 'satuan_id', 'discount', 'is_vat'], 'integer'],
            [['barang_id', 'quantity', 'satuan_id'], 'required'],
            [['stock', 'quantity', 'unit_price'], 'number'],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']],
            [['proforma_invoice_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ProformaInvoice::class, 'targetAttribute' => ['proforma_invoice_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'proforma_invoice_id' => 'Proforma Invoice ID',
            'barang_id' => 'Barang ID',
            'stock' => 'Stock',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
            'unit_price' => 'Unit Price',
            'discount' => 'Discount',
            'is_vat' => 'Is Vat',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProformaInvoice()
    {
        return $this->hasOne(\app\models\ProformaInvoice::class, ['id' => 'proforma_invoice_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }




}
