<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "proforma_invoice_detail_service".
 *
 * @property integer $id
 * @property integer $proforma_invoice_id
 * @property string $job_description
 * @property string $hours
 * @property string $rate_per_hour
 * @property integer $discount
 * @property integer $is_vat
 *
 * @property \app\models\ProformaInvoice $proformaInvoice
 * @property string $aliasModel
 */
abstract class ProformaInvoiceDetailService extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'proforma_invoice_detail_service';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['proforma_invoice_id', 'discount', 'is_vat'], 'integer'],
            [['job_description'], 'required'],
            [['hours', 'rate_per_hour'], 'number'],
            [['job_description'], 'string', 'max' => 255],
            [['proforma_invoice_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ProformaInvoice::class, 'targetAttribute' => ['proforma_invoice_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'proforma_invoice_id' => 'Proforma Invoice ID',
            'job_description' => 'Job Description',
            'hours' => 'Hours',
            'rate_per_hour' => 'Rate Per Hour',
            'discount' => 'Discount',
            'is_vat' => 'Is Vat',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProformaInvoice()
    {
        return $this->hasOne(\app\models\ProformaInvoice::class, ['id' => 'proforma_invoice_id']);
    }




}
