<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "purchase_order".
 *
 * @property integer $id
 * @property string $nomor
 * @property string $tanggal
 * @property string $remarks
 * @property integer $approved_by_id
 * @property integer $acknowledge_by_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\Card $acknowledgeBy
 * @property \app\models\Card $approvedBy
 * @property \app\models\MaterialRequisitionDetailPenawaran[] $materialRequisitionDetailPenawarans
 * @property string $aliasModel
 */
abstract class PurchaseOrder extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_order';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['tanggal', 'approved_by_id', 'acknowledge_by_id'], 'required'],
            [['tanggal'], 'safe'],
            [['remarks'], 'string'],
            [['approved_by_id', 'acknowledge_by_id'], 'integer'],
            [['nomor'], 'string', 'max' => 128],
            [['acknowledge_by_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['acknowledge_by_id' => 'id']],
            [['approved_by_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['approved_by_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nomor' => 'Nomor',
            'tanggal' => 'Tanggal',
            'remarks' => 'Remarks',
            'approved_by_id' => 'Approved By ID',
            'acknowledge_by_id' => 'Acknowledge By ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcknowledgeBy()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'acknowledge_by_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApprovedBy()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'approved_by_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaterialRequisitionDetailPenawarans()
    {
        return $this->hasMany(\app\models\MaterialRequisitionDetailPenawaran::class, ['purchase_order_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\PurchaseOrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\PurchaseOrderQuery(get_called_class());
    }


}
