<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "quotation_term_and_condition".
 *
 * @property integer $id
 * @property integer $quotation_id
 * @property string $term_and_condition
 *
 * @property \app\models\Quotation $quotation
 * @property string $aliasModel
 */
abstract class QuotationTermAndCondition extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_term_and_condition';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['quotation_id'], 'integer'],
            [['term_and_condition'], 'required'],
            [['term_and_condition'], 'string'],
            [['quotation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Quotation::class, 'targetAttribute' => ['quotation_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'quotation_id' => 'Quotation ID',
            'term_and_condition' => 'Term And Condition',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotation()
    {
        return $this->hasOne(\app\models\Quotation::class, ['id' => 'quotation_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\QuotationTermAndConditionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\QuotationTermAndConditionQuery(get_called_class());
    }


}
