<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "quotation_service".
 *
 * @property integer $id
 * @property integer $quotation_id
 * @property string $job_description
 * @property string $hours
 * @property string $rate_per_hour
 * @property integer $discount
 * @property integer $is_vat
 *
 * @property \app\models\Quotation $quotation
 * @property string $aliasModel
 */
abstract class QuotationService extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_service';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['quotation_id', 'discount', 'is_vat'], 'integer'],
            [['job_description'], 'required'],
            [['hours', 'rate_per_hour'], 'number'],
            [['job_description'], 'string', 'max' => 255],
            [['quotation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Quotation::class, 'targetAttribute' => ['quotation_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'quotation_id' => 'Quotation ID',
            'job_description' => 'Job Description',
            'hours' => 'Hours',
            'rate_per_hour' => 'Rate Per Hour',
            'discount' => 'Discount',
            'is_vat' => 'Is Vat',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotation()
    {
        return $this->hasOne(\app\models\Quotation::class, ['id' => 'quotation_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\QuotationServiceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\QuotationServiceQuery(get_called_class());
    }


}
