<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "quotation_form_job_mekanik".
 *
 * @property integer $id
 * @property integer $quotation_form_job_id
 * @property integer $mekanik_id
 *
 * @property \app\models\Card $mekanik
 * @property \app\models\QuotationFormJob $quotationFormJob
 * @property string $aliasModel
 */
abstract class QuotationFormJobMekanik extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_form_job_mekanik';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['quotation_form_job_id', 'mekanik_id'], 'integer'],
            [['mekanik_id'], 'required'],
            [['mekanik_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['mekanik_id' => 'id']],
            [['quotation_form_job_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\QuotationFormJob::class, 'targetAttribute' => ['quotation_form_job_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'quotation_form_job_id' => 'Quotation Form Job ID',
            'mekanik_id' => 'Mekanik ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMekanik()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'mekanik_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationFormJob()
    {
        return $this->hasOne(\app\models\QuotationFormJob::class, ['id' => 'quotation_form_job_id']);
    }




}
