<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\active_queries\SetoranKasirQuery;

/**
 * This is the base-model class for table "setoran_kasir".
 *
 * @property integer $id
 * @property string $reference_number
 * @property string $tanggal_setoran
 * @property integer $cashier_id
 * @property string $staff_name
 * @property integer $bukti_penerimaan_buku_bank_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\BuktiPenerimaanBukuBank $buktiPenerimaanBukuBank
 * @property \app\models\Cashier $cashier
 * @property \app\models\SetoranKasirDetail[] $setoranKasirDetails
 */
abstract class SetoranKasir extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'setoran_kasir';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['tanggal_setoran', 'cashier_id', 'staff_name'], 'required'],
            [['tanggal_setoran'], 'safe'],
            [['cashier_id', 'bukti_penerimaan_buku_bank_id'], 'integer'],
            [['reference_number', 'staff_name'], 'string', 'max' => 50],
            [['cashier_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Cashier::class, 'targetAttribute' => ['cashier_id' => 'id']],
            [['bukti_penerimaan_buku_bank_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BuktiPenerimaanBukuBank::class, 'targetAttribute' => ['bukti_penerimaan_buku_bank_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'reference_number' => 'Reference Number',
            'tanggal_setoran' => 'Tanggal Setoran',
            'cashier_id' => 'Cashier ID',
            'staff_name' => 'Staff Name',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'bukti_penerimaan_buku_bank_id' => 'Bukti Penerimaan Buku Bank ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuktiPenerimaanBukuBank()
    {
        return $this->hasOne(\app\models\BuktiPenerimaanBukuBank::class, ['id' => 'bukti_penerimaan_buku_bank_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashier()
    {
        return $this->hasOne(\app\models\Cashier::class, ['id' => 'cashier_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSetoranKasirDetails()
    {
        return $this->hasMany(\app\models\SetoranKasirDetail::class, ['setoran_kasir_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return SetoranKasirQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SetoranKasirQuery(static::class);
    }
}
