<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\SetoranKasirDetailQuery;

/**
 * This is the base-model class for table "setoran_kasir_detail".
 *
 * @property integer $id
 * @property integer $setoran_kasir_id
 * @property integer $payment_method_id
 * @property integer $quantity
 * @property string $total
 *
 * @property \app\models\PaymentMethod $paymentMethod
 * @property \app\models\SetoranKasir $setoranKasir
 */
abstract class SetoranKasirDetail extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'setoran_kasir_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['setoran_kasir_id', 'payment_method_id', 'quantity'], 'integer'],
            [['payment_method_id', 'quantity', 'total'], 'required'],
            [['total'], 'number'],
            [['setoran_kasir_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SetoranKasir::class, 'targetAttribute' => ['setoran_kasir_id' => 'id']],
            [['payment_method_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PaymentMethod::class, 'targetAttribute' => ['payment_method_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'setoran_kasir_id' => 'Setoran Kasir ID',
            'payment_method_id' => 'Payment Method ID',
            'quantity' => 'Quantity',
            'total' => 'Total',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethod()
    {
        return $this->hasOne(\app\models\PaymentMethod::class, ['id' => 'payment_method_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSetoranKasir()
    {
        return $this->hasOne(\app\models\SetoranKasir::class, ['id' => 'setoran_kasir_id']);
    }

    /**
     * @inheritdoc
     * @return SetoranKasirDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SetoranKasirDetailQuery(static::class);
    }
}
