<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "tanda_terima_barang".
 *
 * @property integer $id
 * @property string $nomor
 * @property string $tanggal
 * @property string $catatan
 * @property string $received_by
 * @property string $messenger
 * @property integer $acknowledge_by_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\Card $acknowledgeBy
 * @property \app\models\TandaTerimaBarangDetail[] $tandaTerimaBarangDetails
 * @property string $aliasModel
 */
abstract class TandaTerimaBarang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tanda_terima_barang';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['tanggal', 'received_by', 'messenger', 'acknowledge_by_id'], 'required'],
            [['tanggal'], 'safe'],
            [['catatan'], 'string'],
            [['acknowledge_by_id'], 'integer'],
            [['nomor'], 'string', 'max' => 128],
            [['received_by', 'messenger'], 'string', 'max' => 255],
            [['acknowledge_by_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['acknowledge_by_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nomor' => 'Nomor',
            'tanggal' => 'Tanggal',
            'catatan' => 'Catatan',
            'received_by' => 'Received By',
            'messenger' => 'Messenger',
            'acknowledge_by_id' => 'Acknowledge By ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'received_by' => 'Ketik manual nama penerima',
            'messenger' => 'Ketik manual nama messenger yang mengantarkan barang',
            'acknowledge_by_id' => 'Orang kantor yang mengetahui',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcknowledgeBy()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'acknowledge_by_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTandaTerimaBarangDetails()
    {
        return $this->hasMany(\app\models\TandaTerimaBarangDetail::class, ['tanda_terima_barang_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\TandaTerimaBarangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\TandaTerimaBarangQuery(get_called_class());
    }


}
