<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "tipe_pembelian".
 *
 * @property integer $id
 * @property string $nama
 * @property string $kode
 *
 * @property \app\models\ClaimPettyCashNotaDetail[] $claimPettyCashNotaDetails
 * @property string $aliasModel
 */
abstract class TipePembelian extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tipe_pembelian';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['nama', 'kode'], 'required'],
            [['nama'], 'string', 'max' => 255],
            [['kode'], 'string', 'max' => 64]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'kode' => 'Kode',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClaimPettyCashNotaDetails()
    {
        return $this->hasMany(\app\models\ClaimPettyCashNotaDetail::class, ['tipe_pembelian_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\TipePembelianQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\TipePembelianQuery(get_called_class());
    }


}
