<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\TransaksiMutasiKasPettyCashLainnyaQuery;

/**
 * This is the base-model class for table "transaksi_mutasi_kas_petty_cash_lainnya".
 *
 * @property integer $id
 * @property string $reference_number
 * @property integer $mutasi_kas_petty_cash_id
 * @property integer $card_id
 * @property integer $jenis_pendapatan_id
 * @property integer $jenis_biaya_id
 * @property string $nominal
 * @property string $keterangan
 *
 * @property \app\models\Card $card
 * @property \app\models\JenisBiaya $jenisBiaya
 * @property \app\models\JenisPendapatan $jenisPendapatan
 * @property \app\models\MutasiKasPettyCash $mutasiKasPettyCash
 */
abstract class TransaksiMutasiKasPettyCashLainnya extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transaksi_mutasi_kas_petty_cash_lainnya';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['mutasi_kas_petty_cash_id', 'card_id', 'jenis_pendapatan_id', 'jenis_biaya_id'], 'integer'],
            [['card_id'], 'required'],
            [['nominal'], 'number'],
            [['keterangan'], 'string'],
            [['reference_number'], 'string', 'max' => 50],
            [['mutasi_kas_petty_cash_id'], 'unique'],
            [['mutasi_kas_petty_cash_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MutasiKasPettyCash::class, 'targetAttribute' => ['mutasi_kas_petty_cash_id' => 'id']],
            [['card_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['card_id' => 'id']],
            [['jenis_pendapatan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JenisPendapatan::class, 'targetAttribute' => ['jenis_pendapatan_id' => 'id']],
            [['jenis_biaya_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JenisBiaya::class, 'targetAttribute' => ['jenis_biaya_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'reference_number' => 'Reference Number',
            'mutasi_kas_petty_cash_id' => 'Mutasi Kas Petty Cash ID',
            'card_id' => 'Card ID',
            'jenis_pendapatan_id' => 'Jenis Pendapatan ID',
            'jenis_biaya_id' => 'Jenis Biaya ID',
            'nominal' => 'Nominal',
            'keterangan' => 'Keterangan',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCard()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'card_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisBiaya()
    {
        return $this->hasOne(\app\models\JenisBiaya::class, ['id' => 'jenis_biaya_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisPendapatan()
    {
        return $this->hasOne(\app\models\JenisPendapatan::class, ['id' => 'jenis_pendapatan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMutasiKasPettyCash()
    {
        return $this->hasOne(\app\models\MutasiKasPettyCash::class, ['id' => 'mutasi_kas_petty_cash_id']);
    }

    /**
     * @inheritdoc
     * @return TransaksiMutasiKasPettyCashLainnyaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransaksiMutasiKasPettyCashLainnyaQuery(static::class);
    }
}
